### ISSUE TITLE
舰娘基本属性和装备基本属性无法使用

### ISSUE THREAD

**Issue by hishi3056** [DK09/blhx-wiki-mirai-plugin#1]
舰娘基本属性和装备基本属性无法使用
大佬是否有时间继续更新呢，可以留下联系方式吗 想跟你联系一下

**Comment by DK09** [comment]
如果是提示图片保存失败，需要在data/blhx-wiki/out目录下创建equip和ship这两个文件夹存放输出图片
![image](https://user-images.githubusercontent.com/22607094/151087388-d2e778e4-1271-467e-b84d-da9ad5c0c0d6.png)
最新项目在https://gitee.com/arisaka-iris/blhx-wiki-mirai-plugin
