### ISSUE TITLE
配装功能错误

### ISSUE THREAD

**Issue by shido2333** [DK09/blhx-wiki-mirai-plugin#11]
![45YZ(R%Q~~KPFW$R TJ6P56](https://user-images.githubusercontent.com/58934221/193780301-52587538-e066-4722-bbe7-1039279d1dd5.png)
环境为mcl-2.1.1

**Comment by KomeijiRan** [comment]
遇到了同样的问题，盲猜可能是碧蓝海事局两千天纪念改了网页UI的问题？

**Comment by DK09** [comment]
这个应该已经修复了，下载最新的jar试一下，有些小bug我没更新版本号，所以看起来像没有更新
