### ISSUE TITLE
怎么设置，BOT的管理员

### ISSUE THREAD

**Issue by Wuyileijv** [DK09/blhx-wiki-mirai-plugin#14]
是真的不会

**Comment by DK09** [comment]
这个机器人没有特殊权限，管理员指令是需要mcl的权限，可以参考https://github.com/mamoe/mirai/blob/dev/mirai-console/docs/BuiltInCommands.md#permissioncommand

**Comment by DK09** [comment]
控制台输入该指令即可
`/perm grant 管理员qq号 org.iris.wiki:*`
另外还需要chat-command插件 https://github.com/project-mirai/chat-command/releases
