### ISSUE TITLE
某些舰船信息无法搜索

### ISSUE THREAD

**Issue by gimfia** [DK09/blhx-wiki-mirai-plugin#3]
![image](https://user-images.githubusercontent.com/54408388/153361802-e0f1093c-0561-482a-8d03-c2afc8ec80a2.png)

**Comment by gimfia** [comment]
好像是带改造的都会这样

**Comment by DK09** [comment]
已修复（wiki界面又双叒改了）
![I`_TI LCQ)F$7HENJJ0`6KW](https://user-images.githubusercontent.com/22607094/153371924-caddbd11-4694-4925-9a0e-f60276233be1.jpg)
