### ISSUE TITLE
可以考虑在查询舰船的时候，直接把推荐装备放在图里

### ISSUE THREAD

**Issue by gimfia** [DK09/blhx-wiki-mirai-plugin#4]
![类似这样](https://user-images.githubusercontent.com/54408388/153362580-8e12ef46-6d93-4f88-880e-36f995a6b6a1.jpg)

**Comment by gimfia** [comment]
类似这样

**Comment by DK09** [comment]
懒得加了，而且打轻甲和重甲带的主炮/飞机是不一样的

**Comment by gimfia** [comment]
> 懒得加了，而且打轻甲和重甲带的主炮/飞机是不一样的

那可以考虑一下，把wiki xx 配装，图里的配装，把wiki上特殊的配装给加上
![image](https://user-images.githubusercontent.com/54408388/153526333-4827196c-8c0e-4c61-9741-b1b94708562f.png)
就上面红框的部分，目前是这样的
![~{5CDSJCXBPV8~XP_H~L`2E](https://user-images.githubusercontent.com/54408388/153526394-b262f385-be5d-4161-9ca6-1821ff16413b.png)

**Comment by DK09** [comment]
更新了
