### ISSUE TITLE
wiki [舰娘]、wiki [装备] 指令无法生成舰娘、装备图片

### ISSUE THREAD

**Issue by kino-xyl** [DK09/blhx-wiki-mirai-plugin#6]
使用环境：windows server2019、mcl 2.0.1 amd64、blhx-wiki v0.3.10、其他插件（mirai-api-http-v2.4.0、chat-command-0.5.1）
wiki [舰娘] wiki [装备] 发送指令无反馈、后台报错。其他指令正常
早前版本插件正常部署过一次，重新部署就出错了。
舰娘报错、异常
![image](https://user-images.githubusercontent.com/76544531/167980517-7c3c242d-e1bf-4723-b7e9-baecc8d220ce.png)
![image](https://user-images.githubusercontent.com/76544531/167980600-6a260dbc-98d1-4b39-94ff-ab633fea9f5c.png)
装备报错、异常
![image](https://user-images.githubusercontent.com/76544531/167981051-279d016f-fbc5-4498-b180-7314aaf04efd.png)
![image](https://user-images.githubusercontent.com/76544531/167981548-432d7b60-83b3-4489-813e-eed2bd6706e7.png)

**Comment by DK09** [comment]
放错包了，还是没有自动生成输出文件夹的版本，现在已经更新，下载最新release jar包即可

**Comment by kino-xyl** [comment]
用的是最新的..
![image](https://user-images.githubusercontent.com/76544531/167991295-5300a4af-75a2-41d1-9766-60bea1b9ce71.png)

**Comment by DK09** [comment]
最新版本我自己测试是没有问题的，实在不行可以手动创建`data\org.iris.wiki\out\equip`以及`data\org.iris.wiki\out\ship`这两个文件夹

**Comment by kino-xyl** [comment]
> 

感谢，解决了！
